openapi: 3.0.3
info:
  title: Customer details
  description: Customer details
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /customers:
    get:
      summary: "Customer detail"
      parameters:
        - in: query
          name: customerId
          schema:
            $ref: uuid
          required: true
        - in: query
          name: month
          schema:
            type: string
          required: false
        - in: query
          name: year
          schema:
            type: string
          required: true
      description: "Get customer details"
      responses:
        '200':
          $ref: '#/components/responses/200'
        '500':
          $ref: '#/components/responses/500'
    post:
      summary: "Customer detail"
      requestBody:
        description: Request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      description: "Get customer details"
      responses:
        '200':
          $ref: '#/components/responses/200'
        '500':
          $ref: '#/components/responses/500'


components:
  responses:
    '200':
      description: "Customer details"
      content:
        application.json:
          schema:
            $ref: '#/components/schemas/CustomerDetails'
    '500':
      description: "error response"
      content:
        application.json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    uuid:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      minLength: 36
      maxLength: 36
    CustomerDetails:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        accounts:
          type: array
          items:
              $ref: '#/components/schemas/Account'
    Account:
      type: object
      properties:
        accountNumber:
          type: string
        balance:
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
    Request:
      type: object
      properties:
        customerId:
          type: string
        month:
          type: string
          required: false
        year:
          type: string
  
